Misc. DLL Decomp (+ setup)
Trouble from MSVC 6.0:
error C2955: use of class template requires template argument list
`near`, `far`, `rad1`, `rad2`, and `WM_NULL` are macros in <windows.h>.